// Mode 09 PIDs
pub const VIN_MESSAGE_COUNT: u8 = 0x01;
pub const VEHICLE_IDENTIFICATION_NUMBER: u8 = 0x02;
pub const CALIBRATION_ID_MESSAGE_COUNT: u8 = 0x03;
pub const CALIBRATION_ID: u8 = 0x04;
pub const CVN_MESSAGE_COUNT: u8 = 0x05;
pub const CALIBRATION_VERIFICATION_NUMBER: u8 = 0x06;
pub const IN_USE_PERFORMANCE_TRACKING_MESSAGE_COUNT: u8 = 0x07;
pub const IN_USE_PERFORMANCE_TRACKING_SPARK: u8 = 0x08;
pub const ECU_NAME_MESSAGE_COUNT: u8 = 0x09;
pub const ECU_NAME: u8 = 0x0A;
pub const IN_USE_PERFORMANCE_TRACKING_COMPRESSION: u8 = 0x0B;
